FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src

COPY ["DentalClinic.Appointments.Domain/DentalClinic.Appointments.Domain.csproj", "DentalClinic.Appointments.Domain/"]
COPY ["DentalClinic.Appointments.Application/DentalClinic.Appointments.Application.csproj", "DentalClinic.Appointments.Application/"]
COPY ["DentalClinic.Appointments.ReadModel/DentalClinic.Appointments.ReadModel.csproj", "DentalClinic.Appointments.ReadModel/"]
COPY ["DentalClinic.Appointments.Projections.Worker/DentalClinic.Appointments.Projections.Worker.csproj", "DentalClinic.Appointments.Projections.Worker/"]

RUN dotnet restore "DentalClinic.Appointments.Projections.Worker/DentalClinic.Appointments.Projections.Worker.csproj"

COPY . .
WORKDIR "/src/DentalClinic.Appointments.Projections.Worker"

RUN dotnet publish "DentalClinic.Appointments.Projections.Worker.csproj" \
    --configuration $BUILD_CONFIGURATION \
    --output /app/publish \
    /p:UseAppHost=false

FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS final
WORKDIR /app

COPY --from=build /app/publish .

ENTRYPOINT ["dotnet", "DentalClinic.Appointments.Projections.Worker.dll"]