<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>a23c1452-100b-49b5-ba33-eba0dd682f72</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\DentalClinic.Appointments.Application\DentalClinic.Appointments.Application.csproj" />
    <ProjectReference Include="..\DentalClinic.Appointments.Infrastructure\DentalClinic.Appointments.Infrastructure.csproj" />
    <ProjectReference Include="..\DentalClinic.Appointments.ReadModel\DentalClinic.Appointments.ReadModel.csproj" />
  </ItemGroup>

</Project>
